
import { AITool } from './types';

export const AI_TOOLS: AITool[] = [
  {
    id: '1',
    name: 'Roboflow',
    category: 'Görsel',
    description: 'Bilgisayarla görme modelleri eğitme platformu.',
    longDescription: 'Görüntüleri etiketlemek, modelleri eğitmek ve uygulamaya koymak için profesyonel bir ekosistem sunar. Eğitim projelerinde nesne tanıma çalışmaları için idealdir.',
    url: 'https://roboflow.com',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '2',
    name: 'Consensus',
    category: 'Araştırma',
    description: 'Bilimsel makale tabanlı AI arama motoru.',
    longDescription: '200 milyondan fazla akademik makaleyi tarayarak sorularınıza bilimsel kanıtlarla cevap verir. Tezler ve akademik araştırmalar için en güvenilir kaynaktır.',
    url: 'https://consensus.app',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '3',
    name: 'Overleaf',
    category: 'Metin',
    description: 'İşbirlikçi LaTeX yazım platformu.',
    longDescription: 'Karmaşık akademik makaleleri ve tezleri bulut tabanlı LaTeX editörü ile yazmanızı sağlar. Aynı anda birden fazla kişi çalışabilir.',
    url: 'https://overleaf.com',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '4',
    name: 'Gemini',
    category: 'Metin',
    description: 'Google\'ın en gelişmiş çok modlu yapay zekası.',
    longDescription: 'Analiz, kodlama, yaratıcı yazarlık ve görsel yorumlama konularında rakipsiz hız ve entegrasyon sunar.',
    url: 'https://gemini.google.com',
    imageUrl: 'https://images.unsplash.com/photo-1676299081847-c0326a0333d5?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '5',
    name: 'NotebookLM',
    category: 'Araştırma',
    description: 'Kendi kaynaklarınızla beslenen AI asistanı.',
    longDescription: 'Yüklediğiniz PDF ve notları analiz eder, onlardan bir podcast veya derinlemesine bir özet oluşturabilir.',
    url: 'https://notebooklm.google.com',
    imageUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '6',
    name: 'HeyGen',
    category: 'Video',
    description: 'Profesyonel AI video ve avatar üretimi.',
    longDescription: 'Sadece metin girerek kendinizi veya bir karakteri konuşturabileceğiniz, dudak senkronizasyonu mükemmel videolar üretir.',
    url: 'https://heygen.com',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '7',
    name: 'MagicSchool',
    category: 'Eğitim',
    description: 'Öğretmenler için hepsi bir arada AI aracı.',
    longDescription: 'Ders planı, rubrik, sınav ve IEP hazırlama gibi öğretmenlerin idari yükünü %90 oranında azaltan bir platformdur.',
    url: 'https://magicschool.ai',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '8',
    name: 'Cursor AI',
    category: 'Kodlama',
    description: 'Geleceğin kod editörü.',
    longDescription: 'Yazılım geliştirme sürecinde kodu anlayan, hatayı düzelten ve sizin yerinize yeni özellikler yazan AI entegreli bir IDE.',
    url: 'https://cursor.com',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '9',
    name: 'Gamma',
    category: 'Verimlilik',
    description: 'Saniyeler içinde sunum ve site hazırlayın.',
    longDescription: 'Sadece bir konu başlığı vererek görsel tasarımı ve içeriği hazır sunum desteleri oluşturmanızı sağlar.',
    url: 'https://gamma.app',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '10',
    name: 'Ideogram AI',
    category: 'Görsel',
    description: 'Tipografide uzman görsel üretim aracı.',
    longDescription: 'Görsellerin içine düzgün ve estetik yazılar ekleme konusunda piyasadaki en başarılı yapay zekadır.',
    url: 'https://ideogram.ai',
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '11',
    name: 'Canva AI',
    category: 'Görsel',
    description: 'Tasarımcı olmayanlar için sihirli araçlar.',
    longDescription: 'Görsel genişletme, nesne silme ve metinden görsele dönüştürme gibi özelliklerle tasarımı demokratikleştirir.',
    url: 'https://canva.com',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '12',
    name: 'Perplexity',
    category: 'Araştırma',
    description: 'Kaynak gösteren AI arama asistanı.',
    longDescription: 'Google araması yerine geçen, sorularınıza kaynak linkleriyle birlikte doğrudan yanıt veren bir bilgi motorudur.',
    url: 'https://perplexity.ai',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '13',
    name: 'Suno AI',
    category: 'Ses',
    description: 'Yüksek kaliteli müzik üretimi.',
    longDescription: 'Şarkı sözlerinizi, tercih ettiğiniz müzik türünde ve profesyonel vokallerle tam bir şarkıya dönüştürür.',
    url: 'https://suno.com',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '14',
    name: 'ElevenLabs',
    category: 'Ses',
    description: 'En doğal seslendirme teknolojisi.',
    longDescription: 'Metni saniyeler içinde insan duygusuna sahip profesyonel seslendirmelere çevirir. Ses klonlama özelliği mevcuttur.',
    url: 'https://elevenlabs.io',
    imageUrl: 'https://images.unsplash.com/photo-1520529011870-5c6b44c0bb8c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '15',
    name: 'Wolfram Alpha',
    category: 'Matematik',
    description: 'Adım adım matematiksel çözüm motoru.',
    longDescription: 'Sadece hesaplama yapmaz, karmaşık denklemleri adım adım çözerek mantığını anlatır.',
    url: 'https://wolframalpha.com',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd482195b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '16',
    name: 'Claude 3.5 Sonnet',
    category: 'Metin',
    description: 'Mantıksal çıkarım ve kodlamanın lideri.',
    longDescription: 'Anthropic tarafından geliştirilen, insansı yazım dili ve üstün akıl yürütme becerilerine sahip model.',
    url: 'https://claude.ai',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '17',
    name: 'Pika Art',
    category: 'Video',
    description: 'Sinematik video animasyon üretimi.',
    longDescription: 'Görselleri veya metinleri hareketli, yüksek kaliteli sinematik videolara dönüştürür.',
    url: 'https://pika.art',
    imageUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '18',
    name: 'Quillbot',
    category: 'Metin',
    description: 'Metinleri yeniden ifade etme ve özetleme.',
    longDescription: 'Akademik veya yaratıcı metinleri anlamını bozmadan farklı kelimelerle yeniden yazar.',
    url: 'https://quillbot.com',
    imageUrl: 'https://images.unsplash.com/photo-1455849318743-b2233052fcff?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '19',
    name: 'SlidesAI',
    category: 'Verimlilik',
    description: 'Metinden anında Google Slides sunumu.',
    longDescription: 'Bir metni veya makaleyi okuyarak içeriğine uygun slaytları otomatik oluşturur.',
    url: 'https://slidesai.io',
    imageUrl: 'https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '20',
    name: 'DeepL',
    category: 'Metin',
    description: 'Dünyanın en iyi AI çeviri aracı.',
    longDescription: 'Anlamsal doğruluğu en yüksek olan çeviri motorudur. Doküman çevirisi de yapabilir.',
    url: 'https://deepl.com',
    imageUrl: 'https://images.unsplash.com/photo-1451187530230-b237ee7091df?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '21',
    name: 'Curipod',
    category: 'Eğitim',
    description: 'Etkileşimli AI dersleri oluşturun.',
    longDescription: 'Öğrencilerin anlık katılım sağlayabileceği, AI destekli interaktif sunumlar hazırlar.',
    url: 'https://curipod.com',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '22',
    name: 'ChatGPT Plus',
    category: 'Metin',
    description: 'Özelleştirilmiş GPT modelleri ve veri analizi.',
    longDescription: 'Kendi GPT\'lerinizi oluşturmanıza ve gelişmiş veri analizi yapmanıza olanak tanıyan standart belirleyici platform.',
    url: 'https://chat.openai.com',
    imageUrl: 'https://images.unsplash.com/photo-1675557009875-436f595b189d?auto=format&fit=crop&q=80&w=400',
    isPopular: true,
  },
  {
    id: '23',
    name: 'Descript',
    category: 'Ses',
    description: 'Metin düzenler gibi ses ve video düzenleyin.',
    longDescription: 'Ses kaydını metne döker, metinde bir kelimeyi sildiğinizde sesi de otomatik düzenler.',
    url: 'https://descript.com',
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '24',
    name: 'Notion AI',
    category: 'Verimlilik',
    description: 'Notlar içinde gömülü AI asistanı.',
    longDescription: 'Not alma sürecinizi hızlandırır, tabloları analiz eder ve metinleri optimize eder.',
    url: 'https://notion.so',
    imageUrl: 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '25',
    name: 'Tome',
    category: 'Verimlilik',
    description: 'Hikaye odaklı AI sunum aracı.',
    longDescription: 'Görselleştirilmiş hikaye anlatımı (storytelling) için tasarlanmış yenilikçi bir sunum platformudur.',
    url: 'https://tome.app',
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '26',
    name: 'Kahoot! AI',
    category: 'Eğitim',
    description: 'Konudan saniyeler içinde quiz oluşturun.',
    longDescription: 'Öğretmenlerin girdiği bir dokümandan veya konudan eğlenceli yarışmalar hazırlar.',
    url: 'https://kahoot.com',
    imageUrl: 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '27',
    name: 'Runway Gen-2',
    category: 'Video',
    description: 'Görselden videoya devrimsel araç.',
    longDescription: 'Hareketsiz resimleri veya sadece metni gerçekçi kısa videolara dönüştüren video üretim motoru.',
    url: 'https://runwayml.com',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '28',
    name: 'Otter.ai',
    category: 'Verimlilik',
    description: 'Toplantı notu ve transkripsiyon.',
    longDescription: 'Online toplantılara katılarak sesleri metne döker ve önemli kararları özetler.',
    url: 'https://otter.ai',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '29',
    name: 'DALL-E 3',
    category: 'Görsel',
    description: 'OpenAI\'ın sanatsal görsel motoru.',
    longDescription: 'Metinsel betimlemeleri son derece detaylı ve sanatsal görsellere dönüştürür.',
    url: 'https://openai.com/dall-e-3',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '30',
    name: 'Loom AI',
    category: 'Video',
    description: 'Video mesajlaşmada AI dokunuşu.',
    longDescription: 'Ekran kayıtlarınızı özetler, başlıklar ekler ve sessiz bölümleri otomatik keser.',
    url: 'https://loom.com',
    imageUrl: 'https://images.unsplash.com/photo-1587560699334-cc4ff634909a?auto=format&fit=crop&q=80&w=400',
  }
];

export const CATEGORIES: string[] = ['Tümü', 'Metin', 'Görsel', 'Video', 'Ses', 'Kodlama', 'Eğitim', 'Araştırma', 'Matematik', 'Verimlilik'];
